version: "3"
services:
  redis:
    image: redis   
    ports:
      - "6379:6379"
    networks:
      - apinet
  api:    
    image: localhost:5000/expensev2    
    ports:
      - "8080:8080"
    networks:
      - apinet    
    depends_on:
      - redis
  gateway:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - apinet
    depends_on:
      - api
networks:
  apinet: